Changed pl.dat to make babel stop breaking
Summary:
Internally, babel uses an abstract format to represent pluralization rules.
Babel keeps these rules inside pickled files in `localedata/`. To check the
pluralization rules, babel unpickles the file for the language it's working
with, compiles the file into a python function representation, and then runs the
resulting `eval`ed function against the number to check which pluralization it
should use.

The polish pluralization rules that were stored were apparently in the wrong
format, and thus when trying to unpickle and use these files, babel throws an
error inside its compilation step like:

    TypeError: cannot concatenate 'str' and 'tuple' objects

Since we use this to translate strings on the website, and recently added a
string in polish to the menu bar (which is included everywhere), every page
would break.

I tried re-downloading the cldr localedata as documented in
69a08f319c9025e9996f8fb97dec17ba7805405f, but the resulting file is in the same
format. I tried forcing babel to download the newer cldr localedata (version 25
vs 23.1) but babel doesn't seem to understand the newer format (maybe a true fix
would involve using the newer data, but modifying babel's import seemed a bit
too intense).

To fix this, I unpickled the pl.dat file using

    data = pickle.load(open("third_party/babel/localedata/pl.dat", "rb"))

I then inspected `data["plural_form"].abstract` (the abstract representation of
the data; note that just evaluating `data["plural_form"]` leads to the error
because `__repr__` automatically calls the compilation process). I looked at the
resulting nested tuples for tuples looking like

    ('range_list', [(('value', (12,)), ('value', (14,)))])

The ones I found were at

    data["plural_form"].abstract[1][1][1][1][1][2]
    data["plural_form"].abstract[1][1][1][0][1][1][1][2]
    data["plural_form"].abstract[1][1][1][0][1][0][1][1][1][2]
    data["plural_form"].abstract[0][1][1][1][1][0][1][2][1]
    data["plural_form"].abstract[0][1][1][0][1][2][1]

I changed the lists (the second elements in each of the tuples) as such:

    [(('value', (12,)), ('value', (14,)))]   =>   [('value', (12,)), ('value', (14,))]

I then repickled the object with

    pickle.dump(data, open("third_party/babel/localedata/pl.dat", "wb"))

Test Plan:
 - Make sure that printing the resulting object works:

    $ python -c 'import pickle; print pickle.load(open("babel/localedata/pl.dat", "rb"))["plural_form"]'
    <PluralRule 'one: n is 1, few: n mod 10 in 2..4 and n mod 100 not in 12..14, many: n is not 1 and n mod 10 in 0..1 or n mod 10 in 5..9 or n mod 100 in 12..14'>

 - Make sure that the website now works with ?lang=pl-pl by loading http://localhost:8080/?lang=pl-pl, and seeing that it doesn't give a 500

 - Make sure that pluralization works now:
   - change the default number of `num_untranslated_children` in topics/render.py:1573 to 4
   - Visit the homepage
   - See that under the topic browser, the text at the bottom says "... 5 tematów ..." for the topics which have 1 untranslated child, and "... 4 tematy ..." for the topics that have 0 (note that 4 and 5 are pluralized differently in polish)

Reviewers: dylan, alpert

Reviewed By: alpert

Subscribers: csilvers, james, alpert

Differential Revision: http://phabricator.khanacademy.org/D12528